In [1]:
import numpy as np
from scipy.fftpack import fft,ifft

In [2]:
x1 = np.array([1.0, 2.0, 1.0, -1.0, 1.5])

In [3]:
# Using scipy
y = fft(x1)

In [4]:
y

array([ 4.5       +0.j        ,  2.08155948-1.65109876j,
       -1.83155948+1.60822041j, -1.83155948-1.60822041j,
        2.08155948+1.65109876j])

In [5]:
idft_y=ifft(y)

In [6]:
idft_y

array([ 1. +0.j,  2. +0.j,  1. +0.j, -1. +0.j,  1.5+0.j])

In [7]:
# Using Numpy
z=np.fft.fft(x1)

In [8]:
z

array([ 4.5       +0.j        ,  2.08155948-1.65109876j,
       -1.83155948+1.60822041j, -1.83155948-1.60822041j,
        2.08155948+1.65109876j])

In [9]:
z_inverse=np.fft.ifft(z)

In [10]:
z_inverse

array([ 1. +0.j,  2. +0.j,  1. +0.j, -1. +0.j,  1.5+0.j])

In [11]:
# User defined function for FFT
def DFT(x):    
    N=x.size
    n=np.arange(N)
    k=n.reshape((N,1))
    e=np.exp(-2j * np.pi * k * n / N)
    return np.dot(e,x)

In [12]:
dft_x=DFT(x1)

In [13]:
dft_x

array([ 4.5       +0.j        ,  2.08155948-1.65109876j,
       -1.83155948+1.60822041j, -1.83155948-1.60822041j,
        2.08155948+1.65109876j])

In [14]:
# User defined Inverse-DFT
def iDFT(a):    
    N=a.size
    n=np.arange(N)
    k=n.reshape((N,1))
    e=np.exp(2j * np.pi * k *n / N)
    return np.dot(e,a)/N

In [15]:
idft_x=iDFT(dft_x)

In [16]:
idft_x

array([ 1. -8.88178420e-17j,  2. +0.00000000e+00j,  1. +0.00000000e+00j,
       -1. +1.33226763e-16j,  1.5+3.55271368e-16j])

In [17]:
# FFT for 2-Dimenstional
T = np.array([[11, 12, 5, 2], [15, 6,10,25], [10, 8, 12, 5], [12,15,8,6]])

In [18]:
T.shape

(4, 4)

In [19]:
fft_T=np.fft.fft(T)

In [20]:
fft_T

array([[30. +0.j,  6.-10.j,  2. +0.j,  6.+10.j],
       [56. +0.j,  5.+19.j, -6. +0.j,  5.-19.j],
       [35. +0.j, -2. -3.j,  9. +0.j, -2. +3.j],
       [41. +0.j,  4. -9.j, -1. +0.j,  4. +9.j]])

In [21]:
ifft_T=np.fft.ifft(fft_T)

In [22]:
ifft_T

array([[11.+0.j, 12.+0.j,  5.+0.j,  2.+0.j],
       [15.+0.j,  6.+0.j, 10.+0.j, 25.+0.j],
       [10.+0.j,  8.+0.j, 12.+0.j,  5.+0.j],
       [12.+0.j, 15.+0.j,  8.+0.j,  6.+0.j]])