In [1]:
import numpy as np
from scipy.fftpack import fft,ifft

In [2]:
x1 = np.array([1.0, 2.0, 1.0, -1.0, 1.5])

In [3]:
# Using scipy
y = fft(x1)

In [4]:
y

array([ 4.5       +0.j        ,  2.08155948-1.65109876j,
       -1.83155948+1.60822041j, -1.83155948-1.60822041j,
        2.08155948+1.65109876j])

In [5]:
idft_y=ifft(y)

In [6]:
idft_y

array([ 1. +0.j,  2. +0.j,  1. +0.j, -1. +0.j,  1.5+0.j])

In [7]:
# Using Numpy
z=np.fft.fft(x1)

In [8]:
z

array([ 4.5       +0.j        ,  2.08155948-1.65109876j,
       -1.83155948+1.60822041j, -1.83155948-1.60822041j,
        2.08155948+1.65109876j])

In [9]:
z_inverse=np.fft.ifft(z)

In [10]:
z_inverse

array([ 1. +0.j,  2. +0.j,  1. +0.j, -1. +0.j,  1.5+0.j])

In [ ]:
# User defined function for FFT
def DFT(x):    
    N=x.size
    n=np.arange(N)
    k=n.reshape((N,1))
    e=np.exp(-2j * np.pi * k * n / N)
    return np.dot(e,x)

In [ ]:
dft_x=DFT(x1)

In [ ]:
dft_x

In [ ]:
# User defined Inverse-DFT
def iDFT(a):    
    N=a.size
    n=np.arange(N)
    k=n.reshape((N,1))
    e=np.exp(2j * np.pi * k *n / N)
    return np.dot(e,a)/N

In [ ]:
idft_x=iDFT(dft_x)

In [ ]:
idft_x

In [ ]:
# FFT for 2-Dimenstional
T = np.array([[11, 12, 5, 2], [15, 6,10,25], [10, 8, 12, 5], [12,15,8,6]])

In [ ]:
T.shape

In [ ]:
fft_T=np.fft.fft(T)

In [ ]:
fft_T

In [ ]:
ifft_T=np.fft.ifft(fft_T)

In [ ]:
ifft_T